### ISSUE TITLE
Mouse RIGHT button to erase

### ISSUE THREAD

**Issue by ladofa** [ladofa/thepen#12]
Oh my, why couldn't I think this idea in 3 years using this poor program??????

**Comment by ladofa** [comment]
It has done. After test it will be closed.

**Comment by AstudilloMarillo** [comment]
This is actually brilliant, such a simple and elegant implementation. It works perfectly! I have an idea to compliment this, [made a feature request](https://github.com/ladofa/thepen/issues/13).

Btw, it seems in alpha10 the regular Eraser tool is now buggy/choppy/slow.

**Comment by ladofa** [comment]
> Btw, it seems in alpha10 the regular Eraser tool is now buggy/choppy/slow.

I have not known what are you saying, becouse I couldn't experience that.
I don't know why I couldn't, and why now I can experience it.
Anyway it needs hotfix, wait just few days.

**Comment by ladofa** [comment]
I just fix the eraser bug.
