### ISSUE TITLE
Erasing 1 line of an arrow should erase the entire arrow

### ISSUE THREAD

**Issue by AstudilloMarillo** [ladofa/thepen#14]
A drawn arrow consists of 3 lines, the main line and 2 arrow tip lines. Right now, when you try to erase an arrow, it only erases the specific line of the arrow you hover over. In my opinion, it should remove all 3 lines at the same time, since I consider the arrow to be 1 object.

It's a bit silly that right now when you try to erase the arrow by using the Erase tool on the main line, it leaves the 2 arrow tip lines. It gets tedious having to erase each individual line.

**Comment by ladofa** [comment]
Haha I already know about that and I fully agree you,  that is so silly thing.
When I completed the arrow feature, I thought that is inevitable thing. haha

But now I got an idea how to implement it. I may start this job after a week. ^.~

**Comment by AstudilloMarillo** [comment]
Hahaha, yeah I imagined you would! Take your time :)

**Comment by ladofa** [comment]
Fixed!
