### ISSUE TITLE
Draw Arrow

### ISSUE THREAD

**Issue by AstudilloMarillo** [ladofa/thepen#3]
This is actually a really cool piece of software that I would love to use to replace Epic Pen/Panserpen. There's really only 1 feature missing for me to want to just switch over.

A tool to draw an arrow.

Epic Pen and Panserpen both have this option and I use it all the time. Would love it if you could add this.
I'll make a separate issue with some miscellaneous other stuff I came across, those are not "game-breaking" for me, though.

**Comment by ladofa** [comment]
I got an idea is easy way to implement it.
will be updated soon.

**Comment by AstudilloMarillo** [comment]
> I got an idea is easy way to implement it. will be updated soon.

Sounds wonderful, thank you so much!

**Comment by ladofa** [comment]
I'm working in this way...
When you finish a drawing (mouse up or stylus up) and if shift key is in state of pressing, a arrow tip will be drawed.
When you draw whatever free, or use line drawing tool, it works as same way.
The direction of arrow tip will be calculated by your drawing direction.

**Comment by AstudilloMarillo** [comment]
> I'm working in this way... When you finish a drawing (mouse up or stylus up) and if shift key is in state of pressing, a arrow tip will be drawed. When you draw whatever free, or use line drawing tool, it works as same way. The direction of arrow tip will be calculated by your drawing direction.

That is an interesting way to go about it that I haven't seen before.

I do think there is some merit in having a dedicated arrow-mode though, since with that you could be doing a presentation or something and move the arrow around while drawing it and comment on whatever you're pointing at.

**Comment by ladofa** [comment]
I updated Alpha7, you can check it out.
If you have any other idea for drawing arrow, please let me know and update it.
If you satisfied, this issue may be closed.

When you draw short lines in micro seconds, the arrw will be draw on wrong position. This bug may comes from Microsoft and I may let it be until I got an idea to fix it.

**Comment by AstudilloMarillo** [comment]
> I updated Alpha7, you can check it out.

Nice! The mechanics of using it seem to work fine.

I personally don't really like the thick arrow tip I'm getting though, I would prefer a sleeker looking arrow myself.
![image](https://github.com/ladofa/thepen/assets/136191659/9ff44054-57f4-4bd6-9a5b-cf1179ad52d3)
_this is with the pen set to 20x20_

Also, this version seems to introduce a new bug: I can't change the width or height of a pen any more. When I put in a number it just sets it to 0. If I try to click 'save and close' the application crashes.

**Comment by ladofa** [comment]
I'm glad I saw this message now without falling asleep yet.

I upload hotfix, you can check it on [https://github.com/ladofa/thepen/releases/download/%23thepenalpha/thepen-alpha7.1.zip](https://github.com/ladofa/thepen/releases/download/%23thepenalpha/thepen-alpha7.1.zip)

And I will try to change the shape of the arrow. But now, how about you to change the size of arrow in the setting page? 10 or 8 may be better.

**Comment by AstudilloMarillo** [comment]
> I upload hotfix, you can check it on https://github.com/ladofa/thepen/releases/download/%23thepenalpha/thepen-alpha7.1.zip

Wonderful, hotfix fixed it!



> And I will try to change the shape of the arrow. But now, how about you to change the size of arrow in the setting page? 10 or 8 may be better.

Not sure if this could have an impact or maybe you already took it into consideration, but I use a 1440p monitor so maybe these different sizes would give different results for other resolution monitors? Any way, I'll play around with the sizes for now, thanks! 

> I'm glad I saw this message now without falling asleep yet.

Sleep well!
