### ISSUE TITLE
Miscellaneous issues/feature requests

### ISSUE THREAD

**Issue by AstudilloMarillo** [ladofa/thepen#4]
Here are some things I came across while trying out this great little app.

Bug:
-The question mark button that's in the "hat-menu" doesn't seem to do anything.
-Shapes and Stamps don't seem to work at all for me (at least in Alpha6)
_Never mind, I figured out how they work now with the hotkeys. Although I gotta say, it's a bit confusing that selecting these from the toolbar doesn't seem to do anything._

Feature requests:
-Have a different cursor when the eraser tool is selected.
-Have a configurable hotkey to hide/show the toolbar menu.
-Have the app show up in the system tray (for when you would hide the toolbar menu). Clicking it would show the toolbar menu, right-clicking would give the option to quit ThePen. Maybe have it configurable to show or hide the app in the system tray for if other people wouldn't want this.
-Have matching cursors for the different shapes/stamps.
-Option to write text on the screen

**Comment by ladofa** [comment]
Very huge thanks for your post.
Many features were planned but not implemented and finally forgotten.
Question mark is for help page. I will make another request for it.
Stamp and shapes will be not change. At the firsttime I planed the buttons as toggle switch. It should be delete.

Diffrent cursor for eraser -> listed on my brain. 
hide/show the toolbar -> did you try RIGHT click on the hat?
System tray -> I dealed it first, but I couldn't make it.. It was more complex than I thought. Some day it will be updated.
Different cursor -> Good idea but I don' have extra energy  for it T^T.
Text on the screen -> Good idea .. some day...

**Comment by AstudilloMarillo** [comment]
> hide/show the toolbar -> did you try RIGHT click on the hat?

Ohhh no, I hadn't tried that before, that's neat.

I've actually been daily driving ThePen for the last 2 weeks now, and I really like the responsiveness of it (much faster and more reliable than Epic Pen). It's also really nice that it's such a small file size and that it's portable.

Looking forward to seeing what you manage to do with my suggestions :)

**Comment by ladofa** [comment]
I couldn't find any mouse icon for erasing mode. But I add new feature for it.

I use this software everyday for my lecture, When I erase something, I need to move my stylus in busy. I know all bugs and problems but I didn't think that I should fix it.  I'm very happy now, you gave me big motivations to improve it. Thank you!!

**Comment by AstudilloMarillo** [comment]
> I couldn't find any mouse icon for erasing mode. But I add new feature for it.

I like it! It's nice to see the actual size of the eraser with the circle. Maybe to substitute the fact that you can't find a specific eraser icon, how about this: Flip the pen icon around so that the backside is what you point with. Since the pen already has something kinda resembling an eraser on the back I think it could work visually, and together with the circle surrounding it I think it should be clear how you're supposed to "aim" with it.

> I'm very happy now, you gave me big motivations to improve it. Thank you!!

You're very welcome, I'm glad I can give you motivation, you're a talented programmer :)

**Comment by ladofa** [comment]
> I like it! It's nice to see the actual size of the eraser with the circle. Maybe to substitute the fact that you can't find a specific eraser icon, how about this: Flip the pen icon around so that the backside is what you point with. Since the pen already has something kinda resembling an eraser on the back I think it could work visually, and together with the circle surrounding it I think it should be clear how you're supposed to "aim" with it.

Actually says, the all icons you saw in this program and I searched for the eraser are from default icon sets. I don't want to make custom icon. The benifit of it is that you can see the icon color and size as you set up in the setting page. Above all, I want to make my works as small as possible. 

![Clipboard01](https://github.com/ladofa/thepen/assets/3085225/4ed1f245-2bee-41eb-9bc0-514d163ac482)

![Clipboard02](https://github.com/ladofa/thepen/assets/3085225/39631a38-7dc9-4e2f-98e5-ee9908f618ef)
You can see the default icons in the mouse setting page.

**Comment by AstudilloMarillo** [comment]
> Actually says, the all icons you saw in this program and I searched for the eraser are from default icon sets. I don't want to make custom icon. The benifit of it is that you can see the icon color and size as you set up in the setting page. Above all, I want to make my works as small as possible.

Right, that makes a lot of sense! You should hold on to those ideals, they're a core strength of this application. Looking through the different pointers, I agree there's not really a suitable option. But that's okay, it's already much clearer now with the circle.

**Comment by ladofa** [comment]
I close this issue, something were implemented, something were impossing, something were moved to another issue.
