### ISSUE TITLE
More boards and background covering image

### ISSUE THREAD

**Issue by ladofa** [ladofa/thepen#8]
I have a plan to add these features to ThePen.
 - control 3 boards, each board has own pen style
 - Background that fill all area.

I am also a user of ThePen, as a user, I don't change pen style(shortcut W, E), So instead of changing the pen style, I'm thinking about changing the board.

**Comment by ladofa** [comment]
Let me know if you are drawing while mixing pen styles

**Comment by ladofa** [comment]
It has almost done. After few tests, it will be closed.

**Comment by AstudilloMarillo** [comment]
> Let me know if you are drawing while mixing pen styles

If it helps, I do use different pen styles. Mostly because the drawn arrows don't look right in the width/height of my default pen style, so I made a different pen style just for arrows. But being able to use multiple pen styles is definitely useful.


> It has almost done. After few tests, it will be closed.

I can see how this new feature can be very useful for certain workflows. Not sure if I'd use it myself, but that's fine, of course. I do suggest making a template image for each slot, not only back3. Maybe some actual templates like for example a whiteboard, blackboard and a green-styled-blackboard. Although that will increase the size of the application, so I'd understand If you wouldn't want to do that.

**Comment by ladofa** [comment]
> If it helps, I do use different pen styles. Mostly because the drawn arrows don't look right in the width/height of my default pen style, so I made a different pen style just for arrows. But being able to use multiple pen styles is definitely useful.

Hm ~ If you change your pen and mix pen styles on a board, I will let it be.

When I design ThePen 3 years ago, I thought two way to change pen style
1. Constantly change after pressing. (current style)
2. Temporally change while presesing, if you lift up the key pen style go back to the previous.

If I set the second style on the shift(arrow key), would you be good?

> Maybe some actual templates like for example a whiteboard, blackboard and a green-styled-blackboard.

I just want to make the option dialog as simple, no more options should be added.  I think there are  So I didn't make a option to select image, but I fixed the name of image. It makes easy to understand how it works. I think ThePen already have many good features, but it is not easy to understand how to do. So I'm considering wizard page or tutorial page.

back1.png and back2.png didn't work yet. but it will be possible as soon. Three backboard may be enough for any user and more board may be confusing.

**Comment by AstudilloMarillo** [comment]
> If I set the second style on the shift(arrow key), would you be good?

I think so, but I don't fully understand what you mean, specifically with "shift(arrow key)". If I were to be able to access a secondary Pen style by holding a hotkey, that would be good for me.

> back1.png and back2.png didn't work yet. but it will be possible as soon. Three backboard may be enough for any user and more board may be confusing.

I completely agree with this. Adding a back1.png and back2.png was the only point I was trying to make really.

**Comment by ladofa** [comment]
> > If I set the second style on the shift(arrow key), would you be good?
> 
> I think so, but I don't fully understand what you mean, specifically with "shift(arrow key)". If I were to be able to access a secondary Pen style by holding a hotkey, that would be good for me.
> 
> > back1.png and back2.png didn't work yet. but it will be possible as soon. Three backboard may be enough for any user and more board may be confusing.
> 
> I completely agree with this. Adding a back1.png and back2.png was the only point I was trying to make really.

It has done.

I can explain the operation mechanism, but it is complex to explain, but simple to use.^^
